name: Cypress E2E tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: STEP 1 - Checkout project
        uses: actions/checkout@v4

      - name: STEP 2 - Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: STEP 3 - Install dependencies
        run: npm install

      - name: STEP 4 - Install Juice Shop
        run: docker pull bkimminich/juice-shop:latest

      - name: STEP 5 - Start Juice Shop
        run: docker run -d -p 3000:3000 bkimminich/juice-shop:latest

      - name: STEP 6 - Wait for Juice Shop
        run: npx wait-on http://localhost:3000

      - name: STEP 7 - Run Cypress tests
        run: npx cypress run

      - name: STEP 8 - Zip Cypress report
        if: always()
        run: zip -r cypress-reports.zip cypress/reports

      - name: STEP 9 - Upload artifact GitHub
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress-reports.zip

      - name: STEP 10 - Upload report Google Drive
        if: always()
        uses: Jodebu/upload-to-drive@master
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folder: ${{ secrets.GDRIVE_FOLDER_ID }}
          target: cypress-reports.zip
          name: cypress-reports.zip
