name: Cypress E2E tests
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: STEP 1 - checkout project
        uses: actions/checkout@v4

      - name: STEP 2 - setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: STEP 3 - install dependencies
        run: npm install

      - name: STEP 4 - Install Juice shop
        run: docker pull bkimminich/juice-shop:latest

      - name: STEP 5 - Start Juice shop
        run: docker run -d -p 3000:3000 bkimminich/juice-shop:latest

      - name: STEP 6 - Wwait for juice shop to be ready
        run: npx wait-on http://localhost:3000

      - name: STEP 7 -  Run Cypress tests
        run: npx cypress run

      - name: STEP 8 - Upload cypress report
        if: always()
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true"
          filename: cypress/reports
          name: cypress-reports

      - name: STEP 9 - Upload Screenshots
        if: failure()
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true"
          filename: cypress/screenshots
          name: cypress-screenshots

      - name: STEP 10 - Upload Videos
        if: always()
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true"
          filename: cypress/videos
          name: cypress-videos

      - name: Debug Secret
        run: |
        if [ -n "${{ secrets.GDRIVE_CREDENTIALS }}" ]; then
        echo "SECRET EXISTS"
        else
        echo "SECRET EMPTY"
        fi